#!/usr/bin/env python
# -*- coding: utf-8 -*-
# EASY-INSTALL-ENTRY-SCRIPT: 'multiple-boxes','console_scripts','multiple_boxes'
__requires__ = "protoqa-evaluator"
import re
import sys

from protoqa_evaluator.__main__ import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
